dist: trusty
language: python
matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6

install: 
  - sudo apt-get update
  - sudo apt-get install gcc
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - git clone https://github.com/Joshuaalbert/RadioAstronomyThings.git $HOME/rathings && cd $HOME/rathings && python setup.py install && cd -
  - git clone https://github.com/rilma/TimeUtilities.git $HOME/timeutilities && cd $HOME/timeutilities && python setup.py install && cd -
  - git clone https://github.com/rilma/pyIRI2016.git $HOME/pyiri2016 && cd $HOME/pyiri2016 && python setup.py develop && cd -
  # install PIL for preprocessing tests
  - pip install -r pip-requirements.txt
  - python setup.py -q install
# command to run tests
script: 
  - pytest
