#!/bin/bash

FROM=( 'arrayCenter' 'peakDensity' 'aPrioriModel' 'peakHeight' 'layerDensity' 'startTime' 'stopTime' 'getInterpolant' 'checkIndexing' 'getModelCoordinates' 'getShapedArray' 'getInterpIndex' 'clearCache' 'useCache' 'cacheCount' 'UVWFrame' 'PointingFrame' 'RealData' 'patchNames' 'outDatapack' 'antIdx' 'timeIdx' 'dirIdx' 'antennaLabels' 'setReferenceAntenna' 'selectAntennas' 'flagAntennas' 'selectFacets' 'datapackSel' 'getCenterDirection' 'getCenter' 'FermatClass' 'splitPatches' 'TricubicInterpolation' 'patchDir' 'integrateRay' 'splitAntennas' 'straightLineApprox' 'castRay' 'radioArray' 'neTCI' 'determineInversionDomain' 'plotDataPack' 'ProgressBarClass' 'getDatumIdx' 'getDatum' 'simulatedTEC' 'dataPackObs' 'datapackObs' 'refAntIdx' 'datumIdx' 'dataFolder' 'numThreads' 'dataPack' 'nePert' 'plotTCI' 'aPrioriFile' 'loadFunc' 'nTCI' 'createInitialModel' 'turbulentPerturbation' 'CovarianceClass' 'covC' 'createTurbulentModel' 'radioArray' 'loadArrayFile' 'antennaPos' 'loadPosArray' 'getSunZenithAngle' 'animateTCISlices' 'computeGradient' 'scalar_product' 'numSeconds' 'templateDatapack' 'outputfolder' 'forwardEquation' 'stateFile' 'calcEpsilon' 'mTCI' 'createBFGSDask' 'lineSearch' 'doForwardEquation' 'transferPatchData' 'patchIdx' 'dtecObservations' 'interpNearest' 'prepareDatapack' 'doAdjoint' 'idxMin' 'idx_max' 'sumMask' 'segmentMask' 'sizeCell' 'doGradient' 'datapackSim' 'plotWavefront' 'plotModel' 'animate_results' 'doPlane' 'makeAnimation' 'logSpacing' 'animateSolutions' 'outputFolder' 'arrayFile' 'prepareDataPack' 'addDataDict' 'findFlaggedAntennas' 'flagPatches' 'saveArrayFile' 'getFov' 'calcCenter' 'getAntennaIdx' 'dataDict' 'refAnt' 'outputLabels' 'numAnt' 'numTimes' 'numDir' 'decMean' 'raMean' 'selectAntennaFacets' 'loadFunc' 'saveFunc' 'jacODE' 'eulerODE' 'neModel' 'pertTCI' 'createTurbulentModel' 'calcRays' 'mergeRays' 'calcRays_dask' 'get_shaped_array()' )


TO=( 'array_center' 'peak_density' 'a_priori_model' 'peak_height' 'layer_density' 'start_time' 'stop_time' 'get_interpolant' 'check_indexing' 'get_model_coordinates' 'get_shaped_array' 'get_interp_index' 'clear_cache' 'use_cache' 'cache_count' 'uvw_frame' 'pointing_frame' 'real_data' 'patch_names' 'out_datapack' 'ant_idx' 'time_idx' 'dir_idx' 'antenna_labels' 'set_reference_antenna' 'select_antennas' 'flag_antennas' 'select_facets' 'datapack_sel' 'get_center_direction' 'get_center' 'fermat' 'split_patches' 'tri_cubic' 'patch_dir' 'integrate_ray' 'split_antennas' 'straight_line_approx' 'cast_ray' 'radio_array' 'ne_tci' 'determine_inversion_domain' 'plot_datapack' 'progressbar' 'get_datum_idx' 'get_datum' 'simulate_dtec' 'datapack_obs' 'datapack_obs' 'ref_ant_idx' 'datum_idx' 'data_folder' 'num_threads' 'datapack' 'ne_pert' 'plot_tci' 'a_priori_file' 'load_func' 'n_tci' 'create_initial_model' 'turbulent_perturbation' 'Covariance' 'cov_obj' 'create_turbulent_model' 'radio_array' 'load_array_file' 'antenna_pos' 'load_pos_array' 'get_sun_zenith_angle' 'animate_tci_slices' 'compute_gradient' 'scalar_product' 'num_seconds' 'template_datapack' 'output_folder' 'forward_equation' 'state_file' 'calc_epsilon' 'm_tci' 'create_bfgs_dask' 'line_search' 'do_forward_equation' 'transfer_patch_data' 'patch_idx' 'dtec_observations' 'interp_nearest' 'prepare_datapack' 'do_adjoint' 'idx_min' 'idx_max' 'sum_mask' 'segment_mask' 'size_cell' 'do_gradient' 'datapack_sim' 'plot_wavefront' 'plot_model' 'animate_results' 'do_plane' 'make_animation' 'log_spacing' 'animate_solutions' 'output_folder' 'array_file' 'prepare_datapack' 'add_data_dict' 'find_flagged_antennas' 'flag_directions' 'save_array_file' 'get_fov' 'calc_center' 'get_antenna_idx' 'data_dict' 'ref_ant' 'output_labels' 'num_ant' 'num_time' 'num_dir' 'dec_mean' 'ra_mean' 'select_antennas_facets' 'load_func' 'save_func' 'jac_ode' 'euler_ode' 'ne_model' 'pert_tci' 'create_turbulent_model' 'calc_rays' 'merge_rays' 'calc_rays_dask' 'M' )


for i in $(seq 0 ${#FROM[@]}); do
	echo ${FROM[$i]} ${TO[$i]}
	find . -name '*.py' -execdir sed -i"backup_$i" 's/'${FROM[$i]}'/'${TO[$i]}'/g' {} \;
done

